#!/usr/bin/env python3
"""Shared helpers for Stage A decoding, filtering, deduplication, and family metadata."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import math
import os
from pathlib import Path, PurePosixPath
import re
import tempfile
from typing import Any, Iterable, Iterator

from stage_a_staging_common import StagingError, atomic_write_bytes, atomic_write_json, atomic_write_jsonl, safe_destination, sha256_bytes, sha256_file, suffix_for


WORD_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+(?:\.\d+)?|[^\s]")
SPACE_RE = re.compile(r"\s+")
NUMBER_RE = re.compile(r"\b(?:0x[0-9a-fA-F]+|\d+(?:\.\d+)?)\b")
HEX_RE = re.compile(r"\b[0-9a-fA-F]{8,}\b")
UUID_RE = re.compile(r"\b[0-9a-fA-F]{8}-[0-9a-fA-F-]{27,}\b")
PATH_TOKEN_RE = re.compile(r"[^a-z0-9]+")

HIGH_CONFIDENCE_SECRET_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("private_key", re.compile(r"-----BEGIN (?:RSA |OPENSSH |EC |DSA )?PRIVATE KEY-----")),
    ("github_pat", re.compile(r"\bghp_[A-Za-z0-9_]{30,}\b")),
    ("openai_key", re.compile(r"\bsk-[A-Za-z0-9_-]{32,}\b")),
    ("aws_access_key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
)

PROMPT_INJECTION_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"(?i)\bignore (?:all |any )?(?:previous|prior|earlier) instructions\b"),
    re.compile(r"(?i)\bsystem prompt\b"),
    re.compile(r"(?i)\bdeveloper message\b"),
)

GENERATED_MARKERS: tuple[re.Pattern[str], ...] = (
    re.compile(r"(?im)^[ \t]*(?:[#/*;!\-]+[ \t]*)?(?:this file (?:is|was) )?(?:auto[- ]?generated|automatically generated|generated file)\b[^\n]{0,120}$"),
    re.compile(r"(?im)^[ \t]*(?:[#/*;!\-]+[ \t]*)?do not edit(?: this file)?[.!]?[ \t]*$"),
    re.compile(r"(?im)^[ \t]*(?:[#/*;!\-]+[ \t]*)?generated by [^\n]{1,120}$"),
)

DEFAULT_PATH_REJECT_PARTS = {
    "node_modules", "vendor", "vendored", "third_party", "third-party", "dist", "build", "out",
    "coverage", ".cache", "__pycache__", "snapshots", "snapshot", "baselines",
    "baseline", "generated", "minified", "golden", "testdata", "test_data",
}

DEFAULT_REJECT_NAMES = {
    "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock",
    "cargo.lock", "composer.lock", "changelog", "changelog.md", "news", "news.md",
}

TEXTUAL_SUFFIXES = {
    ".py", ".pyi", ".js", ".mjs", ".cjs", ".ts", ".tsx", ".d.ts", ".ps1", ".psm1", ".psd1",
    ".sql", ".out", ".sgml", ".rst", ".md", ".mdx", ".txt", ".json", ".toml", ".ini", ".yaml",
    ".yml", ".xml", ".html", ".css",
}

CODE_SUFFIXES = {".py", ".pyi", ".js", ".mjs", ".cjs", ".ts", ".tsx", ".d.ts", ".ps1", ".psm1", ".psd1", ".sql"}
DOC_SUFFIXES = {".sgml", ".rst", ".md", ".mdx", ".txt", ".html"}
CONFIG_SUFFIXES = {".json", ".toml", ".ini", ".yaml", ".yml", ".xml"}


@dataclass(frozen=True)
class DecodedText:
    text: str
    encoding: str
    had_bom: bool
    newline_style: str
    control_ratio: float


@dataclass(frozen=True)
class ProtectedItem:
    protected_id: str
    source_kind: str
    text: str
    normalized: str
    shingles: frozenset[int]


@dataclass(frozen=True)
class ProtectedIndex:
    items: tuple[ProtectedItem, ...]
    shingle_to_items: dict[int, tuple[int, ...]]
    short_item_indices: tuple[int, ...]


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    try:
        with path.open("r", encoding="utf-8-sig") as handle:
            for line_number, line in enumerate(handle, 1):
                if not line.strip():
                    continue
                value = json.loads(line)
                if not isinstance(value, dict):
                    raise StagingError(f"{path}:{line_number}: expected JSON object")
                rows.append(value)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise StagingError(f"cannot read JSONL {path}: {exc}") from exc
    return rows


def atomic_write_text(path: Path, text: str) -> None:
    atomic_write_bytes(path, text.encode("utf-8"))


def normalize_text(text: str) -> str:
    return SPACE_RE.sub(" ", text.strip().lower())


def normalize_template_text(text: str) -> str:
    normalized_lines: list[str] = []
    for raw in text.splitlines():
        line = normalize_text(raw)
        if not line:
            continue
        line = UUID_RE.sub("<uuid>", line)
        line = HEX_RE.sub("<hex>", line)
        line = NUMBER_RE.sub("<n>", line)
        normalized_lines.append(line)
    return "\n".join(normalized_lines)


def lexical_tokens(text: str) -> list[str]:
    return [token.lower() for token in WORD_RE.findall(text)]


def stable_hash64(value: str) -> int:
    return int.from_bytes(hashlib.blake2b(value.encode("utf-8"), digest_size=8).digest(), "big")


def shingle_hashes(text: str, width: int = 5, max_shingles: int = 60000) -> frozenset[int]:
    tokens = lexical_tokens(text)
    if len(tokens) < width:
        return frozenset()
    step = max(1, math.ceil((len(tokens) - width + 1) / max_shingles))
    return frozenset(stable_hash64("\x1f".join(tokens[index:index + width])) for index in range(0, len(tokens) - width + 1, step))


def simhash64(text: str, max_tokens: int = 50000) -> int:
    tokens = lexical_tokens(text)
    if len(tokens) > max_tokens:
        step = math.ceil(len(tokens) / max_tokens)
        tokens = tokens[::step]
    if not tokens:
        return 0
    weights = [0] * 64
    for token in tokens:
        value = stable_hash64(token)
        for bit in range(64):
            weights[bit] += 1 if value & (1 << bit) else -1
    result = 0
    for bit, weight in enumerate(weights):
        if weight >= 0:
            result |= 1 << bit
    return result


def hamming_distance(left: int, right: int) -> int:
    return (left ^ right).bit_count()


def simhash_bands(value: int, band_bits: int = 16) -> tuple[tuple[int, int], ...]:
    mask = (1 << band_bits) - 1
    return tuple((index, (value >> (index * band_bits)) & mask) for index in range(64 // band_bits))


def detect_newline_style(payload: bytes) -> str:
    crlf = payload.count(b"\r\n")
    lf = payload.count(b"\n") - crlf
    cr = payload.count(b"\r") - crlf
    kinds = sum(bool(value) for value in (crlf, lf, cr))
    if kinds == 0:
        return "none"
    if kinds > 1:
        return "mixed"
    if crlf:
        return "crlf"
    if lf:
        return "lf"
    return "cr"


def _control_ratio(text: str) -> float:
    if not text:
        return 0.0
    bad = sum(1 for char in text if ord(char) < 32 and char not in "\n\r\t\f")
    return bad / len(text)


def decode_text(payload: bytes, allow_cp1252: bool = True, max_control_ratio: float = 0.001) -> DecodedText:
    if not payload:
        return DecodedText("", "utf-8", False, "none", 0.0)
    if payload.startswith(b"\xff\xfe\x00\x00") or payload.startswith(b"\x00\x00\xfe\xff"):
        encoding = "utf-32"
        had_bom = True
    elif payload.startswith(b"\xff\xfe") or payload.startswith(b"\xfe\xff"):
        encoding = "utf-16"
        had_bom = True
    elif payload.startswith(b"\xef\xbb\xbf"):
        encoding = "utf-8-sig"
        had_bom = True
    else:
        encoding = "utf-8"
        had_bom = False
    try:
        text = payload.decode(encoding, errors="strict")
    except UnicodeDecodeError:
        if not allow_cp1252 or b"\x00" in payload:
            raise StagingError("text is not valid UTF-8/UTF BOM text")
        try:
            text = payload.decode("cp1252", errors="strict")
            encoding = "cp1252"
        except UnicodeDecodeError as exc:
            raise StagingError("text is not valid UTF-8, UTF BOM, or CP1252") from exc
    ratio = _control_ratio(text)
    if "\x00" in text or ratio > max_control_ratio:
        raise StagingError(f"binary-looking decoded text; control_ratio={ratio:.6f}")
    return DecodedText(text, encoding, had_bom, detect_newline_style(payload), ratio)


def normalized_utf8_text(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def path_parts(path: str) -> tuple[str, ...]:
    return tuple(part.lower() for part in PurePosixPath(path).parts)


def path_quality_reason(path: str, source_policy: dict[str, Any]) -> str | None:
    parts = path_parts(path)
    name = PurePosixPath(path).name.lower()
    rejected_parts = set(DEFAULT_PATH_REJECT_PARTS)
    rejected_parts.update(str(item).lower() for item in source_policy.get("reject_path_parts", []))
    allowed_parts = {str(item).lower() for item in source_policy.get("allow_path_parts", [])}
    bad = [part for part in parts if part in rejected_parts and part not in allowed_parts]
    if bad:
        return f"path marker rejected: {bad[0]}"
    rejected_names = set(DEFAULT_REJECT_NAMES)
    rejected_names.update(str(item).lower() for item in source_policy.get("reject_names", []))
    if name in rejected_names:
        return f"low-value filename rejected: {name}"
    for pattern in source_policy.get("reject_path_regexes", []):
        if re.search(str(pattern), path, flags=re.IGNORECASE):
            return f"source path policy rejected: {pattern}"
    return None


def content_statistics(text: str) -> dict[str, Any]:
    lines = text.splitlines()
    nonempty = [line.strip() for line in lines if line.strip()]
    chars = len(text)
    letters = sum(char.isalpha() for char in text)
    printable = sum(char.isprintable() or char in "\n\r\t" for char in text)
    longest = max((len(line) for line in lines), default=0)
    normalized_lines = [normalize_text(line) for line in nonempty]
    unique_lines = len(set(normalized_lines))
    repeated_ratio = 0.0 if not normalized_lines else 1.0 - unique_lines / len(normalized_lines)
    top_line_ratio = 0.0
    if normalized_lines:
        counts: dict[str, int] = {}
        for line in normalized_lines:
            counts[line] = counts.get(line, 0) + 1
        top_line_ratio = max(counts.values()) / len(normalized_lines)
    tokens = lexical_tokens(text)
    return {
        "char_count": chars,
        "line_count": len(lines),
        "nonempty_line_count": len(nonempty),
        "token_count_proxy": len(tokens),
        "letter_ratio": 0.0 if chars == 0 else letters / chars,
        "printable_ratio": 0.0 if chars == 0 else printable / chars,
        "longest_line": longest,
        "repeated_line_ratio": repeated_ratio,
        "top_line_ratio": top_line_ratio,
    }


def quality_findings(path: str, text: str, source_policy: dict[str, Any]) -> tuple[list[str], list[str]]:
    """Return deterministic rejection reasons and human-review reasons."""
    reject: list[str] = []
    review: list[str] = []
    suffix = suffix_for(path)
    stats = content_statistics(text)
    minimum_chars = int(source_policy.get("min_chars", 120 if suffix in DOC_SUFFIXES else 60))
    minimum_tokens = int(source_policy.get("min_tokens", 24 if suffix in DOC_SUFFIXES else 12))
    maximum_chars = int(source_policy.get("max_decoded_chars", 800000))
    if stats["char_count"] < minimum_chars or stats["token_count_proxy"] < minimum_tokens:
        reject.append("too_short_or_low_information")
    if stats["char_count"] > maximum_chars:
        reject.append("decoded_text_too_large")
    if stats["printable_ratio"] < float(source_policy.get("min_printable_ratio", 0.995)):
        reject.append("non_printable_text")
    if stats["longest_line"] > int(source_policy.get("max_line_chars", 20000)):
        reject.append("extreme_line_length")
    if stats["nonempty_line_count"] >= 20 and stats["repeated_line_ratio"] >= float(source_policy.get("reject_repeated_line_ratio", 0.72)):
        reject.append("repeated_template_or_snapshot")
    elif stats["nonempty_line_count"] >= 20 and stats["repeated_line_ratio"] >= float(source_policy.get("review_repeated_line_ratio", 0.48)):
        review.append("high_repeated_line_ratio")
    if stats["nonempty_line_count"] >= 20 and stats["top_line_ratio"] >= 0.50:
        reject.append("single_line_template_dominates")
    if suffix in CONFIG_SUFFIXES and stats["token_count_proxy"] < int(source_policy.get("min_config_tokens", 80)):
        reject.append("low_information_configuration")
    header = "\n".join(text.splitlines()[:40])[:8000]
    generated_hits = [pattern.pattern for pattern in GENERATED_MARKERS if pattern.search(header)]
    if generated_hits:
        if bool(source_policy.get("reject_generated_markers", True)):
            reject.append("generated_file_marker")
        else:
            review.append("generated_file_marker")
    for label, pattern in HIGH_CONFIDENCE_SECRET_PATTERNS:
        if pattern.search(text):
            reject.append(f"possible_secret:{label}")
    if any(pattern.search(text) for pattern in PROMPT_INJECTION_PATTERNS):
        review.append("prompt_injection_language")
    if suffix in TEXTUAL_SUFFIXES and stats["letter_ratio"] < float(source_policy.get("min_letter_ratio", 0.04)):
        reject.append("very_low_language_content")
    return sorted(set(reject)), sorted(set(review))


def source_family(source_id: str, logical_path: str) -> tuple[str, str]:
    """Return a conservative source-local family ID and a human-readable rule."""
    path = PurePosixPath(logical_path)
    text = path.as_posix()
    lower = text.lower()
    stem = path.stem.lower()
    if stem.endswith(".d"):
        stem = stem[:-2]

    def clean(value: str) -> str:
        value = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
        value = re.sub(r"^(?:test|tests)-", "", value)
        value = re.sub(r"-(?:test|tests)$", "", value)
        return value or "root"

    if source_id == "cpython_3_14_6":
        match = re.match(r"Lib/test/test_([^/]+)\.py$", text, re.I)
        if match:
            return f"{source_id}:module:{clean(match.group(1))}", "cpython_test_module"
        match = re.match(r"Doc/library/([^/.]+)", text, re.I)
        if match:
            return f"{source_id}:module:{clean(match.group(1))}", "cpython_library_doc"
        match = re.match(r"Lib/([^/]+)(?:/|\.py)", text, re.I)
        if match:
            return f"{source_id}:module:{clean(match.group(1))}", "cpython_library_module"
        if lower.startswith("doc/tutorial/"):
            return f"{source_id}:tutorial:{clean(stem)}", "cpython_tutorial"

    if source_id == "node_24_18_0":
        match = re.match(r"doc/api/([^/.]+)", text, re.I)
        if match:
            return f"{source_id}:api:{clean(match.group(1))}", "node_api_doc"
        match = re.match(r"lib/([^/.]+)", text, re.I)
        if match:
            return f"{source_id}:api:{clean(match.group(1))}", "node_library_module"
        match = re.match(r"test/parallel/test-([a-z0-9_]+)", lower)
        if match:
            first = match.group(1).split("-")[0]
            return f"{source_id}:api:{clean(first)}", "node_parallel_test"

    if source_id == "postgresql_18_4":
        if "/sql/" in lower or lower.startswith("src/test/regress/sql/"):
            return f"{source_id}:regress:{clean(stem)}", "postgres_sql_test"
        if "/expected/" in lower or lower.startswith("src/test/regress/expected/"):
            return f"{source_id}:regress:{clean(stem)}", "postgres_expected_pair"
        if lower.startswith("doc/src/sgml/"):
            return f"{source_id}:doc:{clean(stem)}", "postgres_doc_file"

    if source_id == "powershell_docs_2026":
        if lower.startswith("reference/7.6/"):
            return f"{source_id}:cmdlet:{clean(stem)}", "powershell_cmdlet_doc"
        if lower.startswith("reference/docs-conceptual/"):
            parent = clean(path.parent.name)
            return f"{source_id}:concept:{parent}", "powershell_concept_section"

    if source_id == "powershell_7_6_3":
        match = re.search(r"test/powershell/(?:modules|language|engine)/([^/]+)", text, re.I)
        if match:
            return f"{source_id}:area:{clean(match.group(1))}", "powershell_test_area"

    if source_id == "pester_5_7_1":
        for prefix in ("src/", "tst/", "docs/"):
            if lower.startswith(prefix):
                return f"{source_id}:feature:{clean(stem)}", "pester_feature_stem"

    if source_id == "pytest_9_1_1":
        if lower.startswith("src/_pytest/"):
            remainder = PurePosixPath(text[len("src/_pytest/"):])
            feature = remainder.parts[0] if len(remainder.parts) > 1 else stem
            return f"{source_id}:feature:{clean(feature)}", "pytest_source_feature"
        if lower.startswith("testing/"):
            return f"{source_id}:feature:{clean(stem)}", "pytest_test_module"
        if lower.startswith("doc/"):
            return f"{source_id}:doc:{clean(path.parent.name)}", "pytest_doc_section"

    if source_id == "typescript_website_2026":
        parts = path.parts
        if "packages" in parts and len(parts) >= 3:
            package = clean(parts[1])
            return f"{source_id}:package:{package}:{clean(stem)}", "typescript_website_document"

    if source_id == "typescript_6_0_3":
        if lower.startswith("tests/cases/"):
            parent = clean(path.parent.name)
            return f"{source_id}:test-area:{parent}:{clean(stem)}", "typescript_test_case"
        if lower.startswith("src/"):
            parent = clean(path.parent.name)
            return f"{source_id}:source:{parent}:{clean(stem)}", "typescript_source_file"

    parent_parts = [clean(part) for part in path.parent.parts[-2:] if clean(part) not in {"src", "lib", "doc", "docs", "test", "tests"}]
    parent_key = "/".join(parent_parts) if parent_parts else "root"
    return f"{source_id}:path:{parent_key}:{clean(stem)}", "path_stem_fallback"


def extract_strings(value: Any) -> Iterator[str]:
    if isinstance(value, str):
        if value.strip():
            yield value.strip()
    elif isinstance(value, list):
        for item in value:
            yield from extract_strings(item)
    elif isinstance(value, dict):
        for item in value.values():
            yield from extract_strings(item)


def load_protected_items(repo_root: Path) -> list[ProtectedItem]:
    items: list[ProtectedItem] = []
    seen: set[tuple[str, str]] = set()

    def add(source_kind: str, protected_id: str, text: str, min_chars: int) -> None:
        normalized = normalize_text(text)
        if len(normalized) < min_chars:
            return
        key = (source_kind, normalized)
        if key in seen:
            return
        seen.add(key)
        items.append(ProtectedItem(protected_id, source_kind, text, normalized, shingle_hashes(text)))

    for path in sorted((repo_root / "data" / "eval").glob("*.jsonl")):
        for index, row in enumerate(load_jsonl(path), 1):
            row_id = str(row.get("id") or f"row_{index}")
            for field, value in row.items():
                for text in extract_strings(value):
                    add("evaluation", f"{path.name}:{row_id}:{field}", text, 24)

    for path in sorted((repo_root / "data" / "incoming").glob("phase3_5b_batch*_accepted.jsonl")):
        for index, row in enumerate(load_jsonl(path), 1):
            row_id = str(row.get("id") or f"row_{index}")
            for field in ("instruction", "answer", "bad_code", "reasoning", "constraints", "edge_cases"):
                for text in extract_strings(row.get(field)):
                    add("instruction", f"{path.name}:{row_id}:{field}", text, 60)

    tag_pattern = re.compile(r"<(instruction|constraints|answer|bad_code|reasoning)(?:\s[^>]*)?>(.*?)</\1>", re.I | re.S)
    for path in sorted((repo_root / "data" / "raw").glob("*.txt")):
        if re.match(r"phase3_5b_batch\d+_accepted\.txt$", path.name):
            continue
        try:
            raw = path.read_text(encoding="utf-8-sig")
        except (OSError, UnicodeDecodeError):
            continue
        for index, match in enumerate(tag_pattern.finditer(raw), 1):
            add("instruction", f"{path.name}:legacy_{index}:{match.group(1).lower()}", match.group(2).strip(), 60)
    return items


def build_protected_index(protected: Iterable[ProtectedItem]) -> ProtectedIndex:
    items = tuple(protected)
    mutable: dict[int, list[int]] = {}
    short: list[int] = []
    for index, item in enumerate(items):
        if not item.shingles:
            short.append(index)
            continue
        for shingle in item.shingles:
            mutable.setdefault(shingle, []).append(index)
    return ProtectedIndex(
        items=items,
        shingle_to_items={key: tuple(value) for key, value in mutable.items()},
        short_item_indices=tuple(short),
    )


def leakage_findings(text: str, protected: Iterable[ProtectedItem] | ProtectedIndex) -> list[dict[str, Any]]:
    index = protected if isinstance(protected, ProtectedIndex) else build_protected_index(protected)
    normalized = normalize_text(text)
    candidate_shingles = shingle_hashes(text, max_shingles=250000)
    hit_counts: dict[int, int] = {}
    for shingle in candidate_shingles:
        for item_index in index.shingle_to_items.get(shingle, ()):
            hit_counts[item_index] = hit_counts.get(item_index, 0) + 1
    candidate_indices = set(hit_counts)
    candidate_indices.update(index.short_item_indices)
    findings: list[dict[str, Any]] = []
    for item_index in sorted(candidate_indices):
        item = index.items[item_index]
        exact = bool(item.normalized and item.normalized in normalized)
        overlap = hit_counts.get(item_index, 0)
        containment = overlap / len(item.shingles) if item.shingles else 0.0
        severity: str | None = None
        reason = ""
        if item.source_kind == "evaluation":
            if exact:
                severity, reason = "critical", "exact evaluation text contained"
            elif overlap >= 8 and containment >= 0.80:
                severity, reason = "critical", "near-complete evaluation wording overlap"
            elif overlap >= 8 and containment >= 0.35:
                severity, reason = "review", "partial evaluation wording overlap"
        else:
            if exact and len(item.normalized) >= 120:
                severity, reason = "review", "exact accepted-instruction field contained"
            elif overlap >= 10 and containment >= 0.80:
                severity, reason = "review", "near-complete accepted-instruction overlap"
        if severity:
            findings.append({
                "protected_id": item.protected_id,
                "source_kind": item.source_kind,
                "severity": severity,
                "reason": reason,
                "shingle_overlap": overlap,
                "protected_containment": round(containment, 6),
            })
    findings.sort(key=lambda row: (0 if row["severity"] == "critical" else 1, -row["protected_containment"], row["protected_id"]))
    return findings


def choose_duplicate_status(current: dict[str, Any], prior: dict[str, Any]) -> tuple[str, str]:
    if current["normalized_sha256"] == prior["normalized_sha256"]:
        return "reject", f"exact_normalized_duplicate_of:{prior['record_id']}"
    if current["template_sha256"] == prior["template_sha256"] and current["token_count_proxy"] >= 30:
        return "reject", f"template_duplicate_of:{prior['record_id']}"
    left = int(current["simhash64"], 16)
    right = int(prior["simhash64"], 16)
    length_ratio = max(current["token_count_proxy"], prior["token_count_proxy"]) / max(1, min(current["token_count_proxy"], prior["token_count_proxy"]))
    if current["token_count_proxy"] >= 60 and length_ratio <= 1.20 and hamming_distance(left, right) <= 3:
        return "reject", f"near_duplicate_of:{prior['record_id']}"
    if current["token_count_proxy"] >= 40 and length_ratio <= 1.35 and hamming_distance(left, right) <= 6:
        return "review", f"possible_near_duplicate_of:{prior['record_id']}"
    return "keep", ""


def record_fingerprints(text: str) -> dict[str, Any]:
    normalized = normalize_text(text)
    template = normalize_template_text(text)
    return {
        "decoded_sha256": sha256_bytes(text.encode("utf-8")),
        "normalized_sha256": sha256_bytes(normalized.encode("utf-8")),
        "template_sha256": sha256_bytes(template.encode("utf-8")),
        "simhash64": f"{simhash64(text):016x}",
        "token_count_proxy": len(lexical_tokens(text)),
    }


def safe_record_path(root: Path, source_id: str, logical_path: str) -> Path:
    return safe_destination(root / source_id / "files", logical_path)


def manifest_digest(paths: Iterable[Path]) -> str:
    digest = hashlib.sha256()
    for path in sorted(paths, key=lambda item: "/".join(item.parts[-2:])):
        label = "/".join(path.parts[-2:])
        digest.update(label.encode("utf-8"))
        digest.update(b"\0")
        digest.update(sha256_file(path).encode("ascii"))
        digest.update(b"\n")
    return digest.hexdigest()
